### ISSUE TITLE
hl.Api.rethrow does not give full stack

### ISSUE THREAD

**Issue by Gama11** [vshaxe/hashlink-debugger#42]
Here's the callstack I get when the debugger breaks on the exception:

![](https://i.imgur.com/DCPYhXG.png)

But this is what I get on the command line:

![](https://i.imgur.com/cdIrNWz.png)

Shouldn't they match?

**Comment by ncannasse** [comment]
They should. But it seems in the VSCode case, the error is caught by Stage.__handleError and then rethrow. If there's a try/catch, not sure why it's not caught in commandline...

**Comment by ncannasse** [comment]
Ah, maybe it's indeed caught & rethrow, but in the VSCode case the stack "up" from rethrow is not displayed. Uhm... I have to try reproducing this. Do you have the same result using the Node commandline debugger or is it only the HL one?

**Comment by Gama11** [comment]
Well, I can't debug OpenFL in Node.. :)

**Comment by ncannasse** [comment]
Ok, it seems that indeed hl.Api.rethrow does not gives full stack trace in the debugger.
Some when you said "commandline" you meant running hl in the commandline, not when using the commandline debugger :) And when I said node, I was meaning using the node commandline debugger ;)

**Comment by ncannasse** [comment]
It can easily be reproduced by running this in debugger:

```haxe
class Main {

	static function foo( x : Int ) : Int {
		if( x < 0 ) throw "!";
		return foo(x - 1) * 2;
	}

	static function main() {
		try {
			foo(10);
		} catch( e : Dynamic ) {
			hl.Api.rethrow(e);
		}
	}
}
```

**Comment by yuxiaomao** [comment]
It's difficult to display the rethrow stack in call stack section (hard to manage variable inspection because it's not the true stack). But I just implemented the display of rethrow stack in variables section, with 5c257e7914c0d487994db9ceca4e633b815bc08f and 01026854dfcf4873e62effc893ddaa17ad0404c4 . The path given can be used to open file at given location (ctrl+click), I think it's a good enough solution for now.
